name: "FRP Client"
version: "0.1.1"
slug: "frpc"
description: "Runs frpc to expose local services through an frp server"
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
options:
  server_addr: ""
  server_port: 7000
  token: ""
  proxies: []
schema:
  server_addr: str
  server_port: port
  token: password
  proxies:
    - name: str
      type: list(http|tcp|udp)
      local_ip: str
      local_port: port
      custom_domains:
        - str