#!/usr/bin/with-contenv bashio

CONFIG_PATH=/data/options.json
OUT=/tmp/frpc.toml

SERVER_ADDR=$(bashio::config 'server_addr')
SERVER_PORT=$(bashio::config 'server_port')
TOKEN=$(bashio::config 'token')

{
  echo "# Generated by frpc add-on. Do not edit by hand."
  echo "serverAddr = \"${SERVER_ADDR}\""
  echo "serverPort = ${SERVER_PORT}"
  echo "auth.method = \"token\""
  echo "auth.token = \"${TOKEN}\""
  echo ""
} > "$OUT"

# Loop over each proxy entry in options.json and append a [[proxies]] block
jq -c '.proxies[]' "$CONFIG_PATH" | while read -r proxy; do
  name=$(echo "$proxy" | jq -r '.name')
  type=$(echo "$proxy" | jq -r '.type')
  local_ip=$(echo "$proxy" | jq -r '.local_ip')
  local_port=$(echo "$proxy" | jq -r '.local_port')

  {
    echo "[[proxies]]"
    echo "name = \"${name}\""
    echo "type = \"${type}\""
    echo "localIP = \"${local_ip}\""
    echo "localPort = ${local_port}"
    if [ "$type" = "http" ] || [ "$type" = "https" ]; then
      echo "customDomains = [$(echo "$proxy" | jq -r '.custom_domains | map("\"" + . + "\"") | join(", ")')]"
    fi
    echo ""
  } >> "$OUT"
done

bashio::log.info "Generated frpc config with $(jq '.proxies | length' "$CONFIG_PATH") proxies"
bashio::log.info "Starting frpc..."
exec /usr/bin/frpc -c "$OUT"